// <auto-generated />
namespace Smartphones.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create1QW : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create1QW));
        
        string IMigrationMetadata.Id
        {
            get { return "202103232149289_Create1QW"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
